const stageData={s1:{badge:'01',label:'WEEK 1 · OFFLINE',title:'TF 구성 및 착수',desc:'같은 목표를 보고 출발하기 위한 프로젝트 셋업 단계입니다.',items:['구성원 확정','사업 목적·추진 방향 공유','역할 분담','주요 산출물 확정']},s2:{badge:'02',label:'WEEK 2–3 · ON/OFFLINE',title:'업무 분석 및 AI 설계',desc:'현장의 기록 방식을 해체해 AI가 이해할 수 있는 기준으로 바꾸는 핵심 단계입니다.',items:['사례관리 기록 유형·패턴 분석','AI 판단 기준 정리','보고서 어투·미사용 표현 정리','목적별 프롬프트 설계']},s3:{badge:'03',label:'WEEK 4–5 · ON/OFFLINE',title:'결과 테스트 및 보완',desc:'실제 사례를 통해 오류와 한계를 드러내고 현장 활용성을 검증합니다.',items:['실제 사례로 테스트','오류·한계 분석','현장 활용성 검증','프롬프트·출력 형식 수정/보완']},s4:{badge:'04',label:'WEEK 6 · OFFLINE',title:'최종 평가',desc:'성과물을 공유하고 개선 과제와 확대 적용 방향을 결정합니다.',items:['최종 성과물 공유','개선·보완 과제 도출','향후 확대 적용 방향 논의','다음 운영 제안 정리']}};

const tabs=[...document.querySelectorAll('.road-tab')];
const badge=document.getElementById('stageBadge'),label=document.getElementById('stageLabel'),title=document.getElementById('stageTitle'),desc=document.getElementById('stageDesc'),list=document.getElementById('stageList');
tabs.forEach(tab=>tab.addEventListener('click',()=>{tabs.forEach(t=>t.classList.remove('active'));tab.classList.add('active');const d=stageData[tab.dataset.stage];badge.textContent=d.badge;label.textContent=d.label;title.textContent=d.title;desc.textContent=d.desc;list.innerHTML=d.items.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}));

const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.1});
document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));

const progress=document.getElementById('scrollProgress');window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-window.innerHeight;progress.style.width=`${max>0?(window.scrollY/max)*100:0}%`},{passive:true});

const menuBtn=document.getElementById('menuBtn'),mobileNav=document.getElementById('mobileNav');menuBtn.addEventListener('click',()=>mobileNav.classList.toggle('open'));mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobileNav.classList.remove('open')));

const checks=[...document.querySelectorAll('.checklist input[type="checkbox"]')];let savedChecks=[];try{savedChecks=JSON.parse(localStorage.getItem('sck-tf-agreement')||'[]')}catch{}checks.forEach((box,i)=>{box.checked=Boolean(savedChecks[i]);box.addEventListener('change',saveAgreement)});function saveAgreement(){const state=checks.map(b=>b.checked);localStorage.setItem('sck-tf-agreement',JSON.stringify(state));document.getElementById('saveNote').textContent=state.every(Boolean)?'협업 원칙에 모두 체크했습니다. 이 브라우저에 저장되었습니다.':'체크 상태는 이 브라우저에 자동 저장됩니다.'}saveAgreement();

const boardKey='sck-tf-board-v1';let notes=[];try{notes=JSON.parse(localStorage.getItem(boardKey)||'[]')}catch{notes=[]}if(!Array.isArray(notes))notes=[];
const category=document.getElementById('boardCategory'),input=document.getElementById('boardInput'),addBtn=document.getElementById('addNote'),exportBtn=document.getElementById('exportBoard');
function escapeHtml(str){return String(str).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderBoard(){document.querySelectorAll('.note-list').forEach(x=>x.innerHTML='');notes.forEach(note=>{const col=document.querySelector(`.board-col[data-cat="${note.category}"] .note-list`);if(!col)return;const card=document.createElement('article');card.className='sticky-note';card.innerHTML=`<p>${escapeHtml(note.text)}</p><button aria-label="삭제" data-id="${note.id}">×</button>`;col.appendChild(card)});document.querySelectorAll('.sticky-note button').forEach(btn=>btn.addEventListener('click',()=>{notes=notes.filter(n=>String(n.id)!==btn.dataset.id);persistBoard()}))}
function persistBoard(){localStorage.setItem(boardKey,JSON.stringify(notes));renderBoard()}
function addNote(){const text=input.value.trim();if(!text)return;notes.unshift({id:Date.now(),category:category.value,text,createdAt:new Date().toISOString()});input.value='';persistBoard()}
addBtn.addEventListener('click',addNote);input.addEventListener('keydown',e=>{if(e.key==='Enter')addNote()});
exportBtn.addEventListener('click',()=>{const payload={project:'SCK AI Chatbot TF',exportedAt:new Date().toISOString(),notes};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='sck-ai-tf-workshop-board.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});renderBoard();