const stageData={s1:{badge:'01',label:'WEEK 1 · OFFLINE',title:'TF 구성 및 착수',desc:'같은 목표를 보고 출발하기 위한 프로젝트 셋업 단계입니다.',items:['구성원 확정','사업 목적·추진 방향 공유','역할 분담','주요 산출물 확정']},s2:{badge:'02',label:'WEEK 2–3 · ON/OFFLINE',title:'업무 분석 및 AI 설계',desc:'현장의 기록 방식을 해체해 AI가 이해할 수 있는 기준으로 바꾸는 핵심 단계입니다.',items:['사례관리 기록 유형·패턴 분석','AI 판단 기준 정리','보고서 어투·미사용 표현 정리','목적별 프롬프트 설계']},s3:{badge:'03',label:'WEEK 4–5 · ON/OFFLINE',title:'결과 테스트 및 보완',desc:'실제 사례를 통해 오류와 한계를 드러내고 현장 활용성을 검증합니다.',items:['실제 사례로 테스트','오류·한계 분석','현장 활용성 검증','프롬프트·출력 형식 수정/보완']},s4:{badge:'04',label:'WEEK 6 · OFFLINE',title:'최종 평가',desc:'성과물을 공유하고 개선 과제와 확대 적용 방향을 결정합니다.',items:['최종 성과물 공유','개선·보완 과제 도출','향후 확대 적용 방향 논의','다음 운영 제안 정리']}};

function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}

const tabs=[...document.querySelectorAll('.road-tab')];
const badge=document.getElementById('stageBadge'),label=document.getElementById('stageLabel'),title=document.getElementById('stageTitle'),desc=document.getElementById('stageDesc'),list=document.getElementById('stageList');
tabs.forEach(tab=>tab.addEventListener('click',()=>{tabs.forEach(t=>t.classList.remove('active'));tab.classList.add('active');const d=stageData[tab.dataset.stage];badge.textContent=d.badge;label.textContent=d.label;title.textContent=d.title;desc.textContent=d.desc;list.innerHTML=d.items.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}));

const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.1});
document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const progress=document.getElementById('scrollProgress');window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max?scrollY/max*100:0}%`},{passive:true});
const menuBtn=document.getElementById('menuBtn'),mobileNav=document.getElementById('mobileNav');if(menuBtn&&mobileNav){menuBtn.addEventListener('click',()=>mobileNav.classList.toggle('open'));mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobileNav.classList.remove('open')))}
const agreementChecks=[...document.querySelectorAll('.checklist input[type="checkbox"]')];const savedAgreement=JSON.parse(localStorage.getItem('sck-tf-agreement')||'[]');agreementChecks.forEach((box,i)=>{box.checked=!!savedAgreement[i];box.addEventListener('change',()=>{const state=agreementChecks.map(b=>b.checked);localStorage.setItem('sck-tf-agreement',JSON.stringify(state));const n=document.getElementById('saveNote');if(n)n.textContent=state.every(Boolean)?'협업 원칙에 모두 체크했습니다. 이 브라우저에 저장되었습니다.':'체크 상태는 이 브라우저에 자동 저장됩니다.'})});

const css=document.createElement('link');css.rel='stylesheet';css.href='board.css?v=3';document.head.appendChild(css);

const boardSection=document.getElementById('board');
if(boardSection){
  const participantNames=['김홍섭','이영선','최현지','최예린','이호열','서종호','백예원','전현지','이예진','이슬기','김지원','김현주','김자연'];
  const categories={pain:{title:'불편 / 문제',desc:'지금 기록 업무에서 반복되는 어려움'},good:{title:'좋은 기록의 기준',desc:'우리가 지키고 싶은 기록 품질'},ai:{title:'AI가 도와줄 일',desc:'시간을 줄이고 품질을 높일 지점'},risk:{title:'AI가 하면 안 될 일',desc:'사람의 판단이 반드시 필요한 영역'}};
  boardSection.innerHTML=`<div class="shell">
    <div class="wb-toast" id="wbToast"></div>
    <div class="wb-head"><div><span class="section-no">06 / LIVE WORKSHOP BOARD</span><p class="kicker">실시간 협업 보드</p><h2>의견이 올라오는 순간,<br>보드가 같이 움직입니다.</h2></div><div class="wb-status"><i class="wb-dot" id="wbDot"></i><span id="wbStatus">연결 준비 중</span></div></div>
    <div class="wb-topbar"><div class="wb-identity"><label for="wbParticipant">참여자</label><select id="wbParticipant"><option value="">내 이름 선택</option>${participantNames.map(n=>`<option>${n}</option>`).join('')}</select><span class="who" id="wbWho">이름을 선택하면 작성·공감·수정 기능이 활성화됩니다.</span></div><div class="wb-metrics"><div class="wb-metric"><strong id="mNotes">0</strong><span>IDEAS</span></div><div class="wb-metric"><strong id="mPeople">0</strong><span>ACTIVE NOW</span></div><div class="wb-metric"><strong id="mReact">0</strong><span>AGREES</span></div><div class="wb-metric"><strong id="mAuthors">0</strong><span>CONTRIBUTORS</span></div></div></div>
    <div class="wb-composer" id="wbComposer"><select id="wbCategory">${Object.entries(categories).map(([k,v])=>`<option value="${k}">${v.title}</option>`).join('')}</select><textarea id="wbInput" maxlength="280" placeholder="한 가지 생각을 구체적으로 적어주세요. Enter는 줄바꿈, Ctrl+Enter는 등록"></textarea><button class="wb-submit" id="wbSubmit" disabled>의견 등록</button></div>
    <div class="wb-tools"><div class="wb-filters"><button class="wb-chip active" data-filter="all">전체</button>${Object.entries(categories).map(([k,v])=>`<button class="wb-chip" data-filter="${k}">${v.title}</button>`).join('')}</div><div class="wb-actions"><input class="wb-search" id="wbSearch" placeholder="의견·작성자 검색"><button class="wb-tool" id="wbSort">최신순</button><button class="wb-tool" id="wbExport">CSV</button><button class="wb-tool" id="wbPresent">발표 모드</button></div></div>
    <div class="wb-layout"><div class="wb-board" id="wbBoard">${Object.entries(categories).map(([k,v])=>`<section class="wb-col" data-cat="${k}"><div class="wb-col-head"><div class="wb-col-title"><h3>${v.title}</h3><b id="count-${k}">0</b></div><p>${v.desc}</p></div><div class="wb-list" id="list-${k}"></div></section>`).join('')}</div><aside class="wb-side"><div class="wb-panel"><h3>● 지금 접속 중</h3><div class="wb-live-list" id="wbLive"></div></div><div class="wb-panel"><h3>많이 나온 키워드</h3><div class="wb-keywords" id="wbKeywords"></div></div><div class="wb-panel"><h3>최근 활동</h3><div class="wb-activity" id="wbActivity"></div></div></aside></div>
    <p class="wb-section-note">실시간 보드는 Supabase Realtime과 연결되어 있습니다. 같은 링크를 연 참여자들의 등록·수정·공감 내용이 자동으로 반영됩니다.</p>
  </div>`;

  const state={notes:[],reactions:[],presence:[],filter:'all',search:'',sort:'latest',editingId:null,online:false,supabase:null};
  const participantId=localStorage.getItem('sck-wb-participant-id')||((crypto.randomUUID&&crypto.randomUUID())||`p-${Date.now()}-${Math.random().toString(36).slice(2)}`);localStorage.setItem('sck-wb-participant-id',participantId);
  const ownIds=new Set(JSON.parse(localStorage.getItem('sck-wb-own-ids')||'[]'));
  const participant=document.getElementById('wbParticipant'),input=document.getElementById('wbInput'),cat=document.getElementById('wbCategory'),submit=document.getElementById('wbSubmit');
  participant.value=localStorage.getItem('sck-wb-name')||'';
  function currentName(){return participant.value.trim()}
  function updateIdentity(){const name=currentName();localStorage.setItem('sck-wb-name',name);submit.disabled=!name||!input.value.trim();document.getElementById('wbWho').textContent=name?`${name}님으로 참여 중 · 내가 작성한 카드는 수정/삭제할 수 있습니다.`:'이름을 선택하면 작성·공감·수정 기능이 활성화됩니다.';if(name)touchPresence()}
  participant.addEventListener('change',updateIdentity);input.addEventListener('input',updateIdentity);input.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='Enter'){e.preventDefault();submit.click()}});
  const toast=(msg)=>{const el=document.getElementById('wbToast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};
  const age=t=>{const d=Math.max(0,Date.now()-new Date(t).getTime()),m=Math.floor(d/60000);if(m<1)return '방금';if(m<60)return `${m}분 전`;const h=Math.floor(m/60);if(h<24)return `${h}시간 전`;return `${Math.floor(h/24)}일 전`};
  const reactionCounts=()=>state.reactions.reduce((a,r)=>(a[r.note_id]=(a[r.note_id]||0)+1,a),{});
  const myReactionIds=()=>new Set(state.reactions.filter(r=>r.participant_id===participantId).map(r=>r.note_id));
  function visibleNotes(){let arr=state.notes.filter(n=>state.filter==='all'||n.category===state.filter);if(state.search){const q=state.search.toLowerCase();arr=arr.filter(n=>(n.content+' '+n.author_name).toLowerCase().includes(q))}const counts=reactionCounts();return [...arr].sort((a,b)=>state.sort==='popular'?(counts[b.id]||0)-(counts[a.id]||0)||new Date(b.updated_at)-new Date(a.updated_at):new Date(b.updated_at)-new Date(a.updated_at))}
  function render(){const counts=reactionCounts(),mine=myReactionIds(),notes=visibleNotes();Object.keys(categories).forEach(k=>{const list=document.getElementById(`list-${k}`);const group=notes.filter(n=>n.category===k);document.getElementById(`count-${k}`).textContent=state.notes.filter(n=>n.category===k).length;list.innerHTML=group.length?group.map(n=>`<article class="wb-note" data-cat="${n.category}" data-id="${n.id}"><div class="wb-note-top"><div class="wb-author"><span class="wb-avatar">${escapeHtml(n.author_name.slice(0,1))}</span><strong>${escapeHtml(n.author_name)}</strong></div><span class="wb-time">${age(n.updated_at)}</span></div><p class="wb-note-text">${escapeHtml(n.content).replace(/\n/g,'<br>')}</p><div class="wb-note-foot"><button class="wb-react ${mine.has(n.id)?'mine':''}" data-react="${n.id}">♥ 공감 ${counts[n.id]||0}</button>${ownIds.has(n.id)?`<div class="wb-owner-actions"><button class="wb-mini" data-edit="${n.id}" title="수정">✎</button><button class="wb-mini" data-delete="${n.id}" title="삭제">×</button></div>`:''}</div></article>`).join(''):`<div class="wb-empty">아직 의견이 없습니다.<br>첫 카드를 남겨보세요.</div>`});
    document.getElementById('mNotes').textContent=state.notes.length;document.getElementById('mReact').textContent=state.reactions.length;document.getElementById('mAuthors').textContent=new Set(state.notes.map(n=>n.author_name)).size;
    const live=state.presence.filter(p=>Date.now()-new Date(p.last_seen).getTime()<70000);document.getElementById('mPeople').textContent=live.length;document.getElementById('wbLive').innerHTML=live.length?live.sort((a,b)=>a.author_name.localeCompare(b.author_name,'ko')).map(p=>`<div class="wb-live-item"><i></i><span><strong>${escapeHtml(p.author_name)}</strong><br>${p.participant_id===participantId?'나 · 연결됨':'접속 중'}</span></div>`).join(''):'<div class="wb-live-item"><i style="background:#777"></i><span>아직 확인된 참여자가 없습니다.</span></div>';
    renderKeywords();renderActivity();bindCardActions();
  }
  function renderKeywords(){const stop=new Set(['그리고','하지만','대한','위한','있는','없는','있음','필요','기록','사례','사례관리','해야','하는','것이','하면','에서','으로','에게','대해','수','등','것','때문','관련']);const words={};state.notes.forEach(n=>(n.content.match(/[가-힣A-Za-z]{2,}/g)||[]).forEach(w=>{const key=w.toLowerCase();if(!stop.has(key))words[key]=(words[key]||0)+1}));const top=Object.entries(words).sort((a,b)=>b[1]-a[1]).slice(0,12);document.getElementById('wbKeywords').innerHTML=top.length?top.map(([w,c])=>`<span class="wb-keyword">${escapeHtml(w)} <b>${c}</b></span>`).join(''):'<span class="wb-keyword">의견이 쌓이면 자동으로 나타납니다</span>'}
  function renderActivity(){const recent=[...state.notes].sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at)).slice(0,8);document.getElementById('wbActivity').innerHTML=recent.length?recent.map(n=>`<div><strong>${escapeHtml(n.author_name)} · ${escapeHtml(categories[n.category].title)}</strong><span>${escapeHtml(n.content.slice(0,42))}${n.content.length>42?'…':''} · ${age(n.updated_at)}</span></div>`).join(''):'<div><strong>대기 중</strong><span>첫 의견이 올라오면 여기에 표시됩니다.</span></div>'}
  function bindCardActions(){document.querySelectorAll('[data-react]').forEach(b=>b.addEventListener('click',()=>toggleReaction(b.dataset.react)));document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>startEdit(b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>removeNote(b.dataset.delete)))}
  function startEdit(id){const n=state.notes.find(x=>x.id===id);if(!n||!ownIds.has(id))return;state.editingId=id;input.value=n.content;cat.value=n.category;submit.textContent='수정 저장';document.getElementById('wbComposer').classList.add('wb-editing');input.focus();updateIdentity()}
  function endEdit(){state.editingId=null;input.value='';submit.textContent='의견 등록';document.getElementById('wbComposer').classList.remove('wb-editing');updateIdentity()}
  async function submitNote(){const name=currentName(),content=input.value.trim();if(!name||!content)return;if(state.online){submit.disabled=true;let error;if(state.editingId){({error}=await state.supabase.from('sck_tf_workshop_notes').update({content,category:cat.value,author_name:name}).eq('id',state.editingId).eq('editor_token',participantId))}else{const res=await state.supabase.from('sck_tf_workshop_notes').insert({workshop_id:'sck-ai-tf-2026',author_name:name,category:cat.value,content,editor_token:participantId}).select('id').single();error=res.error;if(res.data){ownIds.add(res.data.id);localStorage.setItem('sck-wb-own-ids',JSON.stringify([...ownIds]))}}if(error){toast('저장 중 오류가 발생했습니다.');console.error(error)}else{toast(state.editingId?'의견을 수정했습니다.':'의견을 보드에 등록했습니다.');endEdit();await loadAll()}submit.disabled=false}else{const now=new Date().toISOString();if(state.editingId){const n=state.notes.find(x=>x.id===state.editingId);if(n){n.content=content;n.category=cat.value;n.updated_at=now}}else{const id=(crypto.randomUUID&&crypto.randomUUID())||String(Date.now());state.notes.push({id,author_name:name,category:cat.value,content,created_at:now,updated_at:now});ownIds.add(id);localStorage.setItem('sck-wb-own-ids',JSON.stringify([...ownIds]))}saveLocal();endEdit();render()}}
  submit.addEventListener('click',submitNote);
  async function removeNote(id){if(!ownIds.has(id)||!confirm('이 의견을 삭제할까요?'))return;if(state.online){const {error}=await state.supabase.from('sck_tf_workshop_notes').delete().eq('id',id).eq('editor_token',participantId);if(error){toast('삭제하지 못했습니다.');return}await loadAll()}else{state.notes=state.notes.filter(n=>n.id!==id);state.reactions=state.reactions.filter(r=>r.note_id!==id);saveLocal();render()}ownIds.delete(id);localStorage.setItem('sck-wb-own-ids',JSON.stringify([...ownIds]));toast('삭제했습니다.')}
  async function toggleReaction(noteId){if(!currentName()){toast('먼저 참여자 이름을 선택해주세요.');return}const exists=state.reactions.some(r=>r.note_id===noteId&&r.participant_id===participantId);if(state.online){const res=exists?await state.supabase.from('sck_tf_workshop_reactions').delete().eq('note_id',noteId).eq('participant_id',participantId):await state.supabase.from('sck_tf_workshop_reactions').insert({note_id:noteId,participant_id:participantId});if(res.error){toast('공감을 반영하지 못했습니다.');console.error(res.error)}else await loadAll()}else{state.reactions=exists?state.reactions.filter(r=>!(r.note_id===noteId&&r.participant_id===participantId)):[...state.reactions,{note_id:noteId,participant_id:participantId,created_at:new Date().toISOString()}];saveLocal();render()}}
  document.querySelectorAll('.wb-chip').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.wb-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;render()}));
  document.getElementById('wbSearch').addEventListener('input',e=>{state.search=e.target.value.trim();render()});
  document.getElementById('wbSort').addEventListener('click',e=>{state.sort=state.sort==='latest'?'popular':'latest';e.target.textContent=state.sort==='latest'?'최신순':'공감순';render()});
  document.getElementById('wbPresent').addEventListener('click',e=>{document.body.classList.toggle('wb-presentation');e.target.textContent=document.body.classList.contains('wb-presentation')?'발표 종료':'발표 모드';boardSection.scrollIntoView({behavior:'smooth',block:'start'})});
  document.getElementById('wbExport').addEventListener('click',()=>{const rows=[['구분','작성자','의견','공감','작성시각'],...state.notes.map(n=>[categories[n.category].title,n.author_name,n.content,reactionCounts()[n.id]||0,n.created_at])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='SCK_AI_TF_워크숍보드.csv';a.click();URL.revokeObjectURL(a.href)});
  function saveLocal(){localStorage.setItem('sck-wb-fallback',JSON.stringify({notes:state.notes,reactions:state.reactions}))}
  function loadLocal(){const d=JSON.parse(localStorage.getItem('sck-wb-fallback')||'{"notes":[],"reactions":[]}');state.notes=d.notes||[];state.reactions=d.reactions||[];state.presence=currentName()?[{participant_id:participantId,author_name:currentName(),last_seen:new Date().toISOString()}]:[];render()}
  async function loadAll(){if(!state.online)return;const [n,r,p]=await Promise.all([state.supabase.from('sck_tf_workshop_notes').select('id,author_name,category,content,created_at,updated_at').eq('workshop_id','sck-ai-tf-2026').order('updated_at',{ascending:false}),state.supabase.from('sck_tf_workshop_reactions').select('note_id,participant_id,created_at'),state.supabase.from('sck_tf_workshop_presence').select('participant_id,author_name,last_seen')]);if(n.error||r.error||p.error){console.error(n.error||r.error||p.error);return}state.notes=n.data||[];state.reactions=r.data||[];state.presence=p.data||[];render()}
  async function touchPresence(){if(!state.online||!currentName())return;await state.supabase.from('sck_tf_workshop_presence').upsert({participant_id:participantId,author_name:currentName(),last_seen:new Date().toISOString()},{onConflict:'participant_id'});await loadPresence()}
  async function loadPresence(){if(!state.online)return;const {data}=await state.supabase.from('sck_tf_workshop_presence').select('participant_id,author_name,last_seen');state.presence=data||[];render()}
  let reloadTimer;const scheduleLoad=()=>{clearTimeout(reloadTimer);reloadTimer=setTimeout(loadAll,120)};
  async function initRealtime(){try{const mod=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm');state.supabase=mod.createClient('https://tedbkobhltarqibjhfhk.supabase.co','sb_publishable_CS5rpk5S1eYBFxyUzCQ63w_NzPpwOZ2',{realtime:{params:{eventsPerSecond:20}}});const test=await state.supabase.from('sck_tf_workshop_notes').select('id').limit(1);if(test.error)throw test.error;state.online=true;document.getElementById('wbDot').classList.add('live');document.getElementById('wbStatus').textContent='LIVE · 자동 동기화';await loadAll();await touchPresence();state.supabase.channel('sck-board-live').on('postgres_changes',{event:'*',schema:'public',table:'sck_tf_workshop_notes'},scheduleLoad).on('postgres_changes',{event:'*',schema:'public',table:'sck_tf_workshop_reactions'},scheduleLoad).on('postgres_changes',{event:'*',schema:'public',table:'sck_tf_workshop_presence'},loadPresence).subscribe();setInterval(touchPresence,20000);setInterval(()=>render(),30000)}catch(err){console.warn('Realtime unavailable, fallback to local mode',err);state.online=false;document.getElementById('wbStatus').textContent='LOCAL · 이 기기에서만 저장';loadLocal()}}
  updateIdentity();loadLocal();initRealtime();
}
